name: profile_managemenr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1          # Updated from ^2.24.0
  cloud_firestore: ^6.1.0        # Updated from ^4.14.0
  firebase_auth: ^6.1.2           # Updated from ^4.16.0
  firebase_storage: ^13.0.4       # Updated from ^11.6.0
  image_picker: ^1.0.4        
  permission_handler: ^12.0.1
  provider: ^6.1.1
  loading_animation_widget: ^1.3.0
  speech_to_text: ^7.3.0
  http: ^1.6.0 # or latest
  flutter_dotenv: ^6.0.0 # to store API key securely (optional but recommended)
  google_generative_ai: ^0.4.7
  vibration: ^3.1.4
  camera: ^0.11.3
  google_mlkit_face_detection: ^0.13.1
  image: ^4.1.3
  google_maps_flutter: ^2.5.0 
  geolocator: ^11.0.0
  geocoding: ^2.2.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/widgets/CampusClosetLogo.png
    - .env